version: '3'
services:
  streamlit:
    container_name: streamlitapi
    image: aminehy/docker-streamlit-app:latest
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
  python:
    container_name: python_container
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - streamlit
