version: '3'
services:
  streamlit:
    container_name: streamlitapi
    image: docker.io/bilal326/bda-final-project-streamlitapi:latest
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
   
  python:
    container_name: python_container
    build:
      dockerfile: app/
    volumes:
      - ./app:/app
    depends_on:
      - streamlit
    
