version: '3'
services:
  streamlit:
    container_name: streamlitapi
    image: aminehy/docker-streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - python
  python:
    container_name: python_container
    build:
      dockerfile: Dockerfile.dockerfile
    volumes:
      - ./app:/app
    
